[package]
name = "carambola-tracking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.8.4", features = ["macros"] }
chrono = "0.4.41"
mysql = "26.0.0"
r2d2 = "0.8.10"
redis = { version = "0.31.0", features = ["aio", "disable-client-setinfo", "r2d2", "tokio-comp"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }
tokio-cron-scheduler = "0.14.0"
tower-http = { version = "0.6.5", features = ["compression-full", "decompression-full"] }
yaml-rust2 = "0.10.2"
