[package]
name = "carambola-tracking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.8.1", features = ["macros"] }
chrono = "0.4.39"
r2d2 = "0.8.10"
redis = { version = "0.29.1", features = ["aio", "disable-client-setinfo", "r2d2", "tokio-comp"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_yaml = "0.9.34+deprecated"
tokio = { version = "1.42.0", features = ["full"] }
tokio-cron-scheduler = "0.13.0"
tower-http = { version = "0.6.2", features = ["compression-full", "decompression-full"] }
